<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 9</b></center>
<left><b><h3>Roll No. : 122</b></left>
<left><b><h3>Name : Yatharth Sanghavi</b></left>
<pre>    

In [2]:
!pip install numpy

### 1. Create a NumPy array of 10 student marks and display its `dtype`, `size`, `ndim`, `shape`, `itemsize`, and `nbytes`.

In [3]:
import numpy as np
student=np.array([10,20,30,40,50,60,70,80,90,100])
print(student.dtype)
print(student.size)
print(student.ndim)
print(student.shape)
print(student.itemsize)
print(student.nbytes)

int64
10
1
(10,)
8
80


### 2.Create NumPy arrays using zeros, ones, full, arange, linspace, and identity functions.

In [ ]:
zero=np.zeros(4)
ones=np.ones(4)
full=np.full((2,3),4)
arange=np.arange(1,10)
linspace=np.linspace(1,2,4)
identity=np.identity(3)
print("Zero:",zero)
print("Ones",ones)
print("Full:",full)
print("Arange:",arange)
print("Linspace:",linspace)
print("Identity:",identity)

Zero: [0. 0. 0. 0.]
Ones [1. 1. 1. 1.]
Full: [[4 4 4]
 [4 4 4]]
Arange: [1 2 3 4 5 6 7 8 9]
Linspace: [1.         1.33333333 1.66666667 2.        ]
Identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 3. Create an array of numbers from 1 to 25, reshape it into a 5×5 matrix, and display its transpose.

In [ ]:
r=np.array(range(1,26))
print(r.reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### 4. Generate marks of 20 students randomly between 0 and 100 and find their highest, lowest, and average marks.

In [ ]:
marks=np.random.randint(0,100,20)
print("Highest",marks.max())
print("Lowest",marks.min())
print("Average:",np.average(marks))

Highest 98
Lowest 4
Average: 43.6


### 5. Generate random numbers using `rand()`, `randn()`, `uniform()`, and `normal()`. Use a seed to reproduce the results.

In [ ]:
np.random.seed(1)
rand=np.random.rand()
randn=np.random.randn()
uniform=np.random.uniform()
normal=np.random.normal()
print(rand)
print(randn)
print(uniform)

0.4191945144032948
-1.0170141364670207
0.8781174363909454


### 6. Given roll numbers 101–120, randomly select 5 students without replacement and demonstrate shuffling and permutation.

In [ ]:
student=np.array(range(101,120))
print(np.random.choice(student,5))
np.random.shuffle(student)
print("shuffling:",student)
print("Permutation: ",np.random.permutation(student))

[102 103 113 108 103]
shuffling: [109 104 105 117 113 102 106 119 114 118 112 108 116 115 107 103 110 101
 111]
Permutation:  [105 106 107 101 117 110 116 108 103 118 114 119 109 112 113 111 104 115
 102]


### 7. Given marks of 15 students, calculate sum, mean, median, minimum, maximum, variance, and standard deviation.

In [ ]:
student=np.array(np.random.randint(20,50,15))
print("sum",student.sum())
print("mean",student.mean())
print("median",np.median(student))
print("minimum",student.min())
print("maximum",student.max())
print("Variance",student.var())
print("SD: ",student.std())

sum 507
mean 33.8
median 34.0
minimum 20
maximum 49
Variance 79.89333333333333
SD:  8.938307073116997


### 8. Given daily sales for 10 days, calculate total sales, average sales, cumulative sales, and cumulative product.

In [ ]:
student=np.array(np.random.randint(100,200,10))
print("Total sales:",student.sum())
print("Avg sales: ",np.average(student))
print("Cumulative Sales: ",student.cumsum())
print("Cumulative Product:",student.cumprod())

Total sales: 1497
Avg sales:  149.7
Cumulative Sales:  [ 177  327  506  647  811  994 1118 1238 1382 1497]
Cumulative Product: [                 177                26550              4752450
            670095450         109895653800       20110904645400
     2493752176029600   299250261123552000  6198549454372384768
 -6589831621848264704]


### 9. Create two NumPy arrays and perform addition, subtraction, multiplication, division, floor division, modulus, and exponentiation.

In [ ]:
num1=np.array(np.random.randint(10,20,5))
num2=np.array(np.random.randint(30,40,5))
print("num1",num1,"num2",num2)
print(num1+num2)
print(num2-num1)
print(num1*num2)
print(num2/num1)
print(num2//num1)
print(num1%num2)
print(num1^num2)

num1 [10 16 12 14 13] num2 [36 37 36 33 30]
[46 53 48 47 43]
[26 21 24 19 17]
[360 592 432 462 390]
[3.6        2.3125     3.         2.35714286 2.30769231]
[3 2 3 2 2]
[10 16 12 14 13]
[46 53 40 47 19]


### 10. Create an unsorted array of student marks and display it in ascending and descending order. Also find the sorted indices.

In [ ]:
num1=np.array(np.random.randint(10,20,5))
print(num1)
num1.sort()
print("Ascending", num1)
print("Descending",num1[::-1])
num1.argsort()

[12 16 16 10 11]
Ascending [10 11 12 16 16]
Descending [16 16 12 11 10]


array([0, 1, 2, 3, 4])

### 11. Given the following NumPy array:
Write a program to display:

- First 5 elements
- Last 4 elements
- Elements from index 2 to 6
- Every alternate element

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("First five:",arr[:5])
print("Last Four:",arr[-4:])
print("2 to 6 index",arr[2:7])
print("alternate",arr[::2])

First five: [10 20 30 40 50]
Last Four: [ 70  80  90 100]
2 to 6 index [30 40 50 60 70]
alternate [10 30 50 70 90]


### 12. Given the following NumPy array:
Write a program to display:

- The array in reverse order
- Every second element in reverse order
- Last 5 elements in reverse order

In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
print("Reverse:",arr[::-1])
print("every second element",arr[::-2])
print("last five:",arr[:-5:-1])

Reverse: [50 45 40 35 30 25 20 15 10  5]
every second element [50 40 30 20 10]
last five: [50 45 40 35]


### 13. Given following NumPy Array:
Write a program to display:

- First two rows
- Last two rows
- Alternate rows
- Rows from index 1 to 3

In [ ]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])
print(arr[0:2])
print(arr[:-3:-1])
print(arr[::2])
print(arr[0:3])

[[10 20 30 40]
 [50 60 70 80]]
[[130 140 150 160]
 [ 90 100 110 120]]
[[ 10  20  30  40]
 [ 90 100 110 120]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


### 14. Given following NumPy Array:
Write a program to display:
- First two columns
- Last three columns
- First three rows and last two columns
- A 2×3 sub-array from the center

In [ ]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])
print(arr[::,:2])
print(arr[::,-3::])
print(arr[:3,-2::])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 4  5]
 [ 9 10]
 [14 15]]


### 15. Given following NumPy Array:
Write a program to display:
- The matrix with rows in reverse order
- The matrix with columns in reverse order
- The matrix with both rows and columns reversed
- Alternate rows and alternate columns

In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print(arr[::-1])
print(arr[::,::-1])
print(arr[::-1,::-1])
print(arr[::2,::2])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 1  3]
 [ 9 11]]


### 15. Given an array of marks, write a program to display students who scored more than 75 marks.

In [ ]:
marks = np.array([45, 78, 62, 89, 35, 91, 56, 73, 40, 84])
print(marks[marks>75])

[78 89 91 84]


### 16. Given an array, write a program to display elements that are greater than 30 and less than 70.

In [ ]:
arr = np.array([12, 25, 37, 44, 51, 63, 72, 81, 90, 18])
print(arr[arr>30] and arr[])

[37 44 51 63 72 81 90]


### 17. Given an array, write a program to display elements that are divisible by 5 and greater than 25, and then display elements that are either less than 20 or greater than 45.

In [8]:
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])
print(arr[(arr % 5 == 0) & (arr > 25)])
print(arr[(arr <20 ) | (arr > 45)])

[30 35 40 45 50 55]
[10 15 50 55]
